# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jekyll-Demo
email: info@demo.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
data_dir: ./_data
collections: null

safe: false
include: [".htaccess", "_pages"]
exclude: []
keep_files: [".git", ".gitignore"]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

show_drafts: null
limit_posts: 0
future: true
unpublished: false

whitelist: []
gems: []

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"

detach: false
baseurl: "" # the subpath of your site, e.g. /blog
url: "//gabrysiak.github.io/" # the base hostname & protocol for your site
twitter_username: gabrysiak
github_username:  gabrysiak

permalink: date
paginate_path: /page:num
timezone: null

quiet: false
defaults: []
